server:
  port: 8093
spring:
  application:
    name: shop-upload

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 50
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 192.168.240.128:22122