server:
  port: 8095
spring:
  application:
    name: item-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15